"""Add steps columns to todos table

Revision ID: 4f71ec4dbc11
Revises: 63c4c12eb1a0
Create Date: 2026-01-17 14:28:01.335426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f71ec4dbc11'
down_revision = '63c4c12eb1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('steps', sa.JSON(), nullable=True))
    op.add_column('todos', sa.Column('steps_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('steps_generation_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'steps_generation_status')
    op.drop_column('todos', 'steps_generated_at')
    op.drop_column('todos', 'steps')
    # ### end Alembic commands ###
